### ISSUE TITLE
Write maxp table to fonttools.ttx folder instead of plist?

### ISSUE THREAD

**Issue by madig** [daltonmaag/vttLib#17]
Is there any reason it's written to a plist instead?

**Comment by anthrotype** [comment]
we thought about that, but the problem is the number of glyphs is stored in the maxp and that may change as new glyphs are added or removed from the UFO font. TTX can only merge a table as a whole, so merging in a maxp table with an incorrect number of glyphs would produce a broken font.

**Comment by madig** [comment]
Dumping is now done outside UFOs.
