### ISSUE TITLE
Store TSI1 and TSI3 code in glyph lib, maxp table and shared hinting code (cvt, ...) in font lib

### ISSUE THREAD

**Issue by madig** [daltonmaag/vttLib#19]
The current way of storing big `.ttx` files in the data folder is problematic:

1. Mass changes/updates to the code result in huge diff no one can reasonably check. Smaller changes still hard to check because they are seperated from the glyphs they are supposed to modify.
2. Data folder gets wiped regularly by font editors out there that treat UFO support as a half-baked afterthought.
3. Data folder content has to be encoded as binary data when round-tripping to Glyphs, etc. At least Glyphs 2.4.x we supposedly standardised on internally likes to drop the data (maybe due to the Hex/Base64 bytes issue), Glyphs 2.5 doesn't but might not give exact same result as 2.4.x on some projects.
4. Renaming glyphs requires renaming them in the `.ttx` dumps, too, which is non-obvious and has to be done by hand.

I propose the TSI1/TSI3 data is stored as a glyph lib key (similar to `public.postscript.hints`, in plain string form) and maxp data as a font lib key instead. Maybe a ufo2ft filter can then inject them as it goes?

**Comment by madig** [comment]
Sidenote: how to handle code for variable fonts? Maybe this is taken care of by the `<lib copy="1" />` entry in the designspace document already? What about master-specific CVT data etc., seperate issue?

**Comment by anthrotype** [comment]
Storing that in the glif lib is basically the same way in which Robofont stores similar hinting related data (the “robohint” keys).
I think with Denis we decided to store it in the data folder because it was simpler (just a ttx away). But yeah what you say also makes sense.
Btw, the maxp should already be stored in the lib by vttLib, no? Mainly because ttx can only import whole tables, whereas here we only wanted to merge in a subset of the maxp struct fields, and keep stuff like numGlyphs intact.

**Comment by madig** [comment]
Hm. An alternative is storing the TTX dump as a monolithic blob, but outside the UFO. That way, we lose the 1:1 relationship of source to binary so we can more easily handle generated instances and editors won't delete data/, but one would have to do something about `maxp`.

**Comment by anthrotype** [comment]
i don't see how that would solve the issue of making easier to identify the diffs (1. in the list above)

**Comment by madig** [comment]
Me neither.

**Comment by madig** [comment]
Back on this now. I now think that storing the data in UFO doesn't make sense if you generate instances which may each have different hinting, and you probably need different hinting for variable fonts (overlaps vs. statics without overlaps). Looking into monolithic external blobs now... Ideally we have a "higher level" representation and a VTT compiler, then we can make it human-readable...
