### ISSUE TITLE
Merging without TSI3 and TSI5?

### ISSUE THREAD

**Issue by jenskutilek** [daltonmaag/vttLib#33]
Are TSI3 and TSI5 tables really required to merge/compile a font?

I have some VTT assembly code in TSI1 for which there is no VTTTalk code. Also there are no glyph groups in my font. It should be possible to compile the hinting from the TSI1 table alone, but vttLib currently forces TSI3 and TSI5 to be present (and actually contain data).

**Comment by madig** [comment]
I don't know. The original code may have assumed that you always have them. Try making it work for just TSI1 and see what breaks 😬

**Comment by jenskutilek** [comment]
I worked around this by adding `Quit()` to the VTT talk of all glyphs.

If you just use vttLib, you can get away with omitting the TSI3 table, but if you open the font in VTT later, and recompile the glyph programs, the VTT assembly will be removed. Adding the `Quit()` command prevents that.

**Comment by madig** [comment]
What is `Quit()`?

**Comment by jenskutilek** [comment]
It's the VTTTalk command to stop processing the VTTTalk glyph program, i.e. whatever is in the assembly glyph program will not be overwritten when compiling.
