### ISSUE TITLE
Last release v0.9.1.post2 is not signed

### ISSUE THREAD

**Issue by gagath** [daltonmaag/vttLib#34]
Hello,

In the [release list](https://github.com/daltonmaag/vttLib/releases), the last release to appear is v0.9.1.post2. This seems like a hotfix of the previous release v0.9.1. However this release is not signed.

Given this is the last release that appears on Github, the simplest solution to this problem would be to release a *signed* v0.9.2 release that states that the CI issues have been fixed.

**Comment by madig** [comment]
Hi! I never sign my releases because not signing them works, too 🤷 does that break anything?

**Comment by alerque** [comment]
For a a project like this I don't think not signing releases is particularly a problem. I also have no idea what Romain's use case is, but as a distro packager I can say that in the case of distro packaging the change from signed releases to suddenly *not* signing them can be a problem. At the very least the change needs to be announced, and it's helpful if it's announced in a way that is signed (e.g. "this release is signed, but future releases will not be"). Removing signature checks or disabling them for a release is subject to a lot more scrutiny and red tape than an upstream that never signed anything at all.

**Comment by madig** [comment]
Hm, thanks for the explanation. I had a look at the releases and have no idea why some of them are signed.

**Comment by alerque** [comment]
None of the releases are "signed" in the traditional release signing sense where the artifacts would be checksummed and a signature file would verify that the developer confirmed them.

The only kind of signing being done is that some of the commits are being GPG signed and some are not. When the commit that gets tagged happens to be signed, GitHub is now marking that info on the releases page.

I'm guessing this means you are working from multiple computers and some of them have your GPG private key and Git is configured to use it regularly, others don't. It is also common to see this when people have GitHub configured with their private key but don't have their local systems setup to match. Anything they do from the web UI gets signed, everything else doesn't. Or sometimes the reverse.

Given that most of what I said applies more to release signature files I think you can probably dismiss this. Very few distros care whether commits are signed or not, if the release artifacts aren't being signed it doesn't mean much.

**Comment by gagath** [comment]
Afterall I think signing releases is not that significant. I opened this issue because of [this lintian warning](https://lintian.debian.org/tags/debian-watch-does-not-check-gpg-signature.html) while packaging [python-vttlib](https://tracker.debian.org/pkg/python-vttlib) for Debian. I though that the tarball release could be signed automatically by Github. It cannot. It is the git tag that is signed, not the tarball. It is maybe possible to sign tarballs using Github releases, but I am not sure it is worth the extra time both from the developers and the distribution packagers.

So I think this issue can be closed.
